{"uuid":"56811f25-3e7e-4850-a4dd-552d7b23ee6b","historyId":"e5e4746ad9745ca127979a2a28f513db","fullName":"com.thetestingacademy.VWOLoginTest.testValidLogin","labels":[{"name":"package","value":"com.thetestingacademy.VWOLoginTest"},{"name":"testClass","value":"com.thetestingacademy.VWOLoginTest"},{"name":"testMethod","value":"testValidLogin"},{"name":"parentSuite","value":"Default Suite"},{"name":"suite","value":"VWOLoginAutomationSelenium"},{"name":"subSuite","value":"com.thetestingacademy.VWOLoginTest"},{"name":"host","value":"PC-Sagar-Mohite"},{"name":"thread","value":"4740@PC-Sagar-Mohite.main(1)"},{"name":"framework","value":"testng"},{"name":"language","value":"java"}],"links":[],"name":"testValidLogin","status":"failed","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"expected [https://app.vwo.com/#/dashboard/get-started?accountId=1123587] but found [https://app.vwo.com/#/login]","trace":"java.lang.AssertionError: expected [https://app.vwo.com/#/dashboard/get-started?accountId=1123587] but found [https://app.vwo.com/#/login]\r\n\tat org.testng.Assert.fail(Assert.java:111)\r\n\tat org.testng.Assert.failNotEquals(Assert.java:1578)\r\n\tat org.testng.Assert.assertEqualsImpl(Assert.java:150)\r\n\tat org.testng.Assert.assertEquals(Assert.java:132)\r\n\tat org.testng.Assert.assertEquals(Assert.java:656)\r\n\tat org.testng.Assert.assertEquals(Assert.java:666)\r\n\tat com.thetestingacademy.VWOLoginTest.testValidLogin(VWOLoginTest.java:85)\r\n\tat java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)\r\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:578)\r\n\tat org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)\r\n\tat org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)\r\n\tat org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)\r\n\tat org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)\r\n\tat org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)\r\n\tat org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)\r\n\tat org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)\r\n\tat org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)\r\n\tat java.base/java.util.ArrayList.forEach(ArrayList.java:1511)\r\n\tat org.testng.TestRunner.privateRun(TestRunner.java:819)\r\n\tat org.testng.TestRunner.run(TestRunner.java:619)\r\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:443)\r\n\tat org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)\r\n\tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)\r\n\tat org.testng.SuiteRunner.run(SuiteRunner.java:336)\r\n\tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)\r\n\tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)\r\n\tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)\r\n\tat org.testng.TestNG.runSuitesLocally(TestNG.java:1228)\r\n\tat org.testng.TestNG.runSuites(TestNG.java:1134)\r\n\tat org.testng.TestNG.run(TestNG.java:1101)\r\n\tat com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:65)\r\n\tat com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)\r\n"},"stage":"finished","description":"Verify that with Valid username and Valid password, Login is successfull !!","steps":[],"attachments":[],"parameters":[],"start":1753634961652,"stop":1753635012170}